[package]
name = "webwine-core"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
indexmap = { version = "2", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
goblin = { version = "0.9", default-features = false, features = ["pe32", "pe64"] }
bitflags = "2"
iced-x86 = { version = "1", default-features = false, features = ["std", "decoder"] }
bincode = "1.3.3"
